Mobile menu
mansa-susa/portfolio2 pull request #11
Opened 2022-09-14 15:19 UTC by mansa-susa

- Add an event listener to the mobile menu icon to display the menu mobile
- Add a close button to the mobile menu
- Add an event listener to the close button to close the mobile menu when clicked
- Add an anchor to the sections of the page that links to the menu links
- Add an event listener to the menu links to close the mobile menu pop-up when clicked

2022-09-14 15:42 UTC, Omar-Muhamad reviewed
# Invalid ❌

Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md#:~:text=For%20this%20project%2C%20you%20should%20add%20the%20JavaScript%20%2B%20HTML%20%2B%20CSS%20linter.). Please inculde eslint to linters configuration.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

2022-09-14 16:26 UTC, Ismailco requested changes
### Hi Team, 

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 16:26 UTC, Ismailco commented on main.js
> +function closeMenu() {
- [ ] Kindly fix the horizontal overflow on the page, so the close button on the mobile menu so the close button can be seen without scrolling left and your design look like the Figma design

|Your design|Figma design|
|-|-|
|![Screenshot_20220914_172004](https://user-images.githubusercontent.com/25227022/190209924-acb24b5f-d378-43de-a01d-f6a457e50782.png)|![Screenshot_20220914_172212](https://user-images.githubusercontent.com/25227022/190209925-74850441-88eb-47ba-a169-1af8dd2f7c75.png)|

2022-09-17 18:58 UTC, Kamba56 approved these changes
Hi @mansa-susa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏
👏👏👏


## Highlights
- [x] Great use of github flow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-17 19:02 UTC, merged